name = "World Casper 2"
license = "MIT"
licenselink = "https://github.com/bablem/hugo-world-casper-2/blob/master/LICENSE.md"
description = "Port of Casper 2.x for Hugo, with languages support"
homepage = "https://github.com/bablem/hugo-world-casper-2"
tags = ["blog","pages","ghost theme","i18n","spanish"]
features = ["disqus", "google analytics"]
min_version = 0.31

[author]
  name = "Bablem"
  homepage = "https://www.bablem.com/"

[original]
  name = "Casper"
  homepage = "https://github.com/TryGhost/Casper"
  repo = "https://github.com/TryGhost/Casper"
